### ISSUE TITLE
Issues migrating to 1.15.2

### ISSUE THREAD

**Issue by ghost** [Gerolmed/RealisticTorches#1]
I'm working on a server and this was invaluable for me to understand how to better handle timing out torches. However api changes in Bukkit/Spigot/Paper have really done a number on supporting your extra features. I took my best crack at it over the last day, maybe two.

Did they not replace setTypeIdAndData's location setter after deprecating it? Being outside an event context makes this quite tricky to handle in the block manager in any elegant way when intently avoiding the compositional complexity of querying the world on each block in que for destruction and the incidental block break conditions that go uncaught. All I really needed or want is Air so it works out to me just torturing myself...

If you can advise me on what you know, anything that might help, I'd like to give back. I was trying to implement this feature prior to stumbling on your solution and I'm incredibly grateful at this point but a frustrating port was required. I think theres a possibility that some of the bugs I discovered could reside in your version aswell most likely leaky unlits and a missing block cache remove call that locks a blocks state and additional corner cases. Really not trying to write a book atm.

I think it would be best to abandon the custom meta / unlit entirely, and default to air (until someone from Bukkit realises batch torches can't be mutated into a wall torch properly from a non-event context). In my additions, I handle the wall torch variant, logging is left in, commented out. 

Its nice to meet you after spending so much time learning from your code.

**Comment by ghost** [comment]
For all that, I guess I should be clear that it does work stable, and tested on 1.15.2. If you want to take my changes without a PR.

**Comment by Gerolmed** [comment]
Ill look into updating. I got a lot to do in other projects rn and this was basically just a 1 day coding project. If I do port it I will though remove backwards compatibility and change large structural parts.
If you want to provide improvements or changes feel free to open a PR.

**Comment by ghost** [comment]
Yeah no sense making you go through that. I'll try to get one to you before I goto bed tomorrow.

**Comment by ghost** [comment]
Could I ask you to make a 1.15.2 branch I can PR against since this will definitely break all other versions.

**Comment by Gerolmed** [comment]
Created a 1.15.2 branch

**Comment by ghost** [comment]
Little bit frustrated with the maven packaging system. I haven't forgotten you. Just gotta rebuild it from a new package to match your initial structure first.
